In [7]:
import numpy as np
import time

a=np.random.rand(1000000)
b=np.random.rand(1000000)

tic=time.time()                                 #verctorised  implementation is faster as compared to for loop
c= np.dot(a,b)
toc=time.time()

print(c)
print("Vectorised version:" + str(1000*(toc-tic)) + "ms")

c=0
tic=time.time()
for i in range(1000000):
    c += a[i]*b[i]
toc=time.time()

print(c)
print("For loop:" + str(1000*(toc-tic)) + "ms")

249961.1979118601
Vectorised version:1.001119613647461ms
249961.1979118651
For loop:556.922197341919ms


In [15]:
A= np.array([[56,0,4,68],
             [1.2,104,52,8],
             [1.8,135,99,0.9]])
print(A)

[[ 56.    0.    4.   68. ]
 [  1.2 104.   52.    8. ]
 [  1.8 135.   99.    0.9]]


In [16]:
cal= A.sum(axis=0)
print(cal)

[ 59.  239.  155.   76.9]


In [17]:
percentage= 100*A/cal.reshape(1,4)
print(percentage)

[[94.91525424  0.          2.58064516 88.42652796]
 [ 2.03389831 43.51464435 33.5483871  10.40312094]
 [ 3.05084746 56.48535565 63.87096774  1.17035111]]


In [18]:
a= np.random.rand(5)
print(a)

[0.48410986 0.71601901 0.90077616 0.0481357  0.39619762]


In [19]:
print(a.shape)

(5,)


In [20]:
print(a.T)

[0.48410986 0.71601901 0.90077616 0.0481357  0.39619762]


In [21]:
print(np.dot(a,a.T))

1.7177328769462412


In [26]:
a= np.random.rand(5,1)                     #correct representation
print(a)

[[0.54082668]
 [0.6466684 ]
 [0.01116239]
 [0.11011613]
 [0.13561505]]


In [27]:
print(a.T)

[[0.54082668 0.6466684  0.01116239 0.11011613 0.13561505]]


In [28]:
print(np.dot(a,a.T))

[[2.92493497e-01 3.49735525e-01 6.03692097e-03 5.95537383e-02
  7.33442385e-02]
 [3.49735525e-01 4.18180025e-01 7.21836811e-03 7.12086189e-02
  8.76979696e-02]
 [6.03692097e-03 7.21836811e-03 1.24599060e-04 1.22915968e-03
  1.51378877e-03]
 [5.95537383e-02 7.12086189e-02 1.22915968e-03 1.21255610e-02
  1.49334041e-02]
 [7.33442385e-02 8.76979696e-02 1.51378877e-03 1.49334041e-02
  1.83914425e-02]]


In [30]:
a = np.random.randn(4, 3) # a.shape = (4, 3)
b = np.random.randn(3, 2) # b.shape = (3, 2)
c = a*b

ValueError: operands could not be broadcast together with shapes (4,3) (3,2) 

In [14]:
x=np.exp(a)              #exponential function
y=np.abs(a)              #actual value
print(a)
print(x)
print(y)


[0.11918588 0.08423119 0.65747496 ... 0.0282553  0.4013328  0.91688166]
[1.12657931 1.08788037 1.92991307 ... 1.02865826 1.49381433 2.50147776]
[0.11918588 0.08423119 0.65747496 ... 0.0282553  0.4013328  0.91688166]
